### ISSUE TITLE
nil pointer access by decodeClearsign when parsing garbage

### ISSUE THREAD

**Issue by paultag** [paultag/go-debian#104]
Parsing `-----BEGIN PGP ` as a control file results in a crash

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5626de]

goroutine 1 [running]:
pault.ag/go/debian/control.(*ParagraphReader).decodeClearsig(0xc000010710, 0x0, 0xc0000cf000, 0xf)
	/home/paultag/.goenvs/fuzz/src/pault.ag/go/debian/control/parse.go:294 +0x3ae
pault.ag/go/debian/control.NewParagraphReader(0x5d6a20, 0xc000062240, 0x0, 0x7f036c650000, 0x0, 0x5d6b20)
	/home/paultag/.goenvs/fuzz/src/pault.ag/go/debian/control/parse.go:137 +0x153
pault.ag/go/debian/control.NewDecoder(0x5d6a20, 0xc000062240, 0x0, 0x57d720, 0x10000c000010601, 0x6f22a8)
	/home/paultag/.goenvs/fuzz/src/pault.ag/go/debian/control/decode.go:90 +0x75
pault.ag/go/debian/control.Unmarshal(0x5979c0, 0xc0000947f0, 0x5d6a20, 0xc000062240, 0x0, 0xc0000106f0)
	/home/paultag/.goenvs/fuzz/src/pault.ag/go/debian/control/decode.go:71 +0x5a
pault.ag/go/debian/control.ParseControl(0xc000062240, 0x5b3778, 0x6, 0x4320cf, 0xc000000300, 0x200000003)
	/home/paultag/.goenvs/fuzz/src/pault.ag/go/debian/control/control.go:147 +0x126
_/home/paultag/dev/local/debian-fuzz.Fuzz(0x7f03681fc000, 0xf, 0x200000, 0x3)
	/home/paultag/dev/local/debian-fuzz/debian.go:13 +0xef
go-fuzz-dep.Main(0xc0000a1f80, 0x1, 0x1)
	/tmp/go-fuzz-build890815257/goroot/src/go-fuzz-dep/main.go:36 +0x1b6
main.main()
	/tmp/go-fuzz-build890815257/gopath/src/_/home/paultag/dev/local/debian-fuzz/go.fuzz.main/main.go:15 +0x52
``

**Comment by paultag** [comment]
Thanks, https://github.com/dvyukov/go-fuzz!
